// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgEntity.proto

package com.qingcity.proto;

public final class MsgEntityProto {
  private MsgEntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginCheckOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 msgLength = 1;
    /**
     * <code>required int32 msgLength = 1;</code>
     */
    boolean hasMsgLength();
    /**
     * <code>required int32 msgLength = 1;</code>
     */
    int getMsgLength();

    // required int32 cmdCode = 2;
    /**
     * <code>required int32 cmdCode = 2;</code>
     */
    boolean hasCmdCode();
    /**
     * <code>required int32 cmdCode = 2;</code>
     */
    int getCmdCode();

    // required bytes data = 3;
    /**
     * <code>required bytes data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code LoginCheck}
   */
  public static final class LoginCheck extends
      com.google.protobuf.GeneratedMessage
      implements LoginCheckOrBuilder {
    // Use LoginCheck.newBuilder() to construct.
    private LoginCheck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginCheck(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginCheck defaultInstance;
    public static LoginCheck getDefaultInstance() {
      return defaultInstance;
    }

    public LoginCheck getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginCheck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgLength_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cmdCode_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.MsgEntityProto.internal_static_LoginCheck_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.MsgEntityProto.internal_static_LoginCheck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.MsgEntityProto.LoginCheck.class, com.qingcity.proto.MsgEntityProto.LoginCheck.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginCheck> PARSER =
        new com.google.protobuf.AbstractParser<LoginCheck>() {
      public LoginCheck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginCheck(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginCheck> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 msgLength = 1;
    public static final int MSGLENGTH_FIELD_NUMBER = 1;
    private int msgLength_;
    /**
     * <code>required int32 msgLength = 1;</code>
     */
    public boolean hasMsgLength() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msgLength = 1;</code>
     */
    public int getMsgLength() {
      return msgLength_;
    }

    // required int32 cmdCode = 2;
    public static final int CMDCODE_FIELD_NUMBER = 2;
    private int cmdCode_;
    /**
     * <code>required int32 cmdCode = 2;</code>
     */
    public boolean hasCmdCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cmdCode = 2;</code>
     */
    public int getCmdCode() {
      return cmdCode_;
    }

    // required bytes data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      msgLength_ = 0;
      cmdCode_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmdCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgLength_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cmdCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgLength_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cmdCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.MsgEntityProto.LoginCheck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.MsgEntityProto.LoginCheck prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginCheck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.MsgEntityProto.LoginCheckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.MsgEntityProto.internal_static_LoginCheck_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.MsgEntityProto.internal_static_LoginCheck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.MsgEntityProto.LoginCheck.class, com.qingcity.proto.MsgEntityProto.LoginCheck.Builder.class);
      }

      // Construct using cpgame.demo.proto.MsgEntityProto.LoginCheck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.MsgEntityProto.internal_static_LoginCheck_descriptor;
      }

      public com.qingcity.proto.MsgEntityProto.LoginCheck getDefaultInstanceForType() {
        return com.qingcity.proto.MsgEntityProto.LoginCheck.getDefaultInstance();
      }

      public com.qingcity.proto.MsgEntityProto.LoginCheck build() {
        com.qingcity.proto.MsgEntityProto.LoginCheck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.MsgEntityProto.LoginCheck buildPartial() {
        com.qingcity.proto.MsgEntityProto.LoginCheck result = new com.qingcity.proto.MsgEntityProto.LoginCheck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgLength_ = msgLength_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmdCode_ = cmdCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.MsgEntityProto.LoginCheck) {
          return mergeFrom((com.qingcity.proto.MsgEntityProto.LoginCheck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.MsgEntityProto.LoginCheck other) {
        if (other == com.qingcity.proto.MsgEntityProto.LoginCheck.getDefaultInstance()) return this;
        if (other.hasMsgLength()) {
          setMsgLength(other.getMsgLength());
        }
        if (other.hasCmdCode()) {
          setCmdCode(other.getCmdCode());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgLength()) {
          
          return false;
        }
        if (!hasCmdCode()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.MsgEntityProto.LoginCheck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.MsgEntityProto.LoginCheck) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 msgLength = 1;
      private int msgLength_ ;
      /**
       * <code>required int32 msgLength = 1;</code>
       */
      public boolean hasMsgLength() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msgLength = 1;</code>
       */
      public int getMsgLength() {
        return msgLength_;
      }
      /**
       * <code>required int32 msgLength = 1;</code>
       */
      public Builder setMsgLength(int value) {
        bitField0_ |= 0x00000001;
        msgLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgLength = 1;</code>
       */
      public Builder clearMsgLength() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgLength_ = 0;
        onChanged();
        return this;
      }

      // required int32 cmdCode = 2;
      private int cmdCode_ ;
      /**
       * <code>required int32 cmdCode = 2;</code>
       */
      public boolean hasCmdCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cmdCode = 2;</code>
       */
      public int getCmdCode() {
        return cmdCode_;
      }
      /**
       * <code>required int32 cmdCode = 2;</code>
       */
      public Builder setCmdCode(int value) {
        bitField0_ |= 0x00000002;
        cmdCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmdCode = 2;</code>
       */
      public Builder clearCmdCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdCode_ = 0;
        onChanged();
        return this;
      }

      // required bytes data = 3;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoginCheck)
    }

    static {
      defaultInstance = new LoginCheck(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LoginCheck)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginCheck_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginCheck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MsgEntity.proto\">\n\nLoginCheck\022\021\n\tmsgLe" +
      "ngth\030\001 \002(\005\022\017\n\007cmdCode\030\002 \002(\005\022\014\n\004data\030\003 \002(" +
      "\014B#\n\021cpgame.demo.protoB\016MsgEntityProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LoginCheck_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LoginCheck_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoginCheck_descriptor,
              new java.lang.String[] { "MsgLength", "CmdCode", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
