// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pk.proto

package com.qingcity.proto;

public final class PkMsg {
  private PkMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PkInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 playerId = 1;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int32 playerId = 1;</code>
     */
    int getPlayerId();

    // required int32 musicId = 2;
    /**
     * <code>required int32 musicId = 2;</code>
     */
    boolean hasMusicId();
    /**
     * <code>required int32 musicId = 2;</code>
     */
    int getMusicId();
  }
  /**
   * Protobuf type {@code PkInfo}
   */
  public static final class PkInfo extends
      com.google.protobuf.GeneratedMessage
      implements PkInfoOrBuilder {
    // Use PkInfo.newBuilder() to construct.
    private PkInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PkInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PkInfo defaultInstance;
    public static PkInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PkInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PkInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              musicId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.PkMsg.internal_static_PkInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.PkMsg.internal_static_PkInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.PkMsg.PkInfo.class, com.qingcity.proto.PkMsg.PkInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PkInfo> PARSER =
        new com.google.protobuf.AbstractParser<PkInfo>() {
      public PkInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PkInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PkInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    // required int32 musicId = 2;
    public static final int MUSICID_FIELD_NUMBER = 2;
    private int musicId_;
    /**
     * <code>required int32 musicId = 2;</code>
     */
    public boolean hasMusicId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 musicId = 2;</code>
     */
    public int getMusicId() {
      return musicId_;
    }

    private void initFields() {
      playerId_ = 0;
      musicId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMusicId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, musicId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, musicId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.PkMsg.PkInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.PkMsg.PkInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.PkMsg.PkInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PkInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.PkMsg.PkInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.PkMsg.internal_static_PkInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.PkMsg.internal_static_PkInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.PkMsg.PkInfo.class, com.qingcity.proto.PkMsg.PkInfo.Builder.class);
      }

      // Construct using com.qingcity.proto.PkMsg.PkInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        musicId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.PkMsg.internal_static_PkInfo_descriptor;
      }

      public com.qingcity.proto.PkMsg.PkInfo getDefaultInstanceForType() {
        return com.qingcity.proto.PkMsg.PkInfo.getDefaultInstance();
      }

      public com.qingcity.proto.PkMsg.PkInfo build() {
        com.qingcity.proto.PkMsg.PkInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.PkMsg.PkInfo buildPartial() {
        com.qingcity.proto.PkMsg.PkInfo result = new com.qingcity.proto.PkMsg.PkInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.musicId_ = musicId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.PkMsg.PkInfo) {
          return mergeFrom((com.qingcity.proto.PkMsg.PkInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.PkMsg.PkInfo other) {
        if (other == com.qingcity.proto.PkMsg.PkInfo.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasMusicId()) {
          setMusicId(other.getMusicId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasMusicId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.PkMsg.PkInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.PkMsg.PkInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 playerId = 1;
      private int playerId_ ;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // required int32 musicId = 2;
      private int musicId_ ;
      /**
       * <code>required int32 musicId = 2;</code>
       */
      public boolean hasMusicId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 musicId = 2;</code>
       */
      public int getMusicId() {
        return musicId_;
      }
      /**
       * <code>required int32 musicId = 2;</code>
       */
      public Builder setMusicId(int value) {
        bitField0_ |= 0x00000002;
        musicId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 musicId = 2;</code>
       */
      public Builder clearMusicId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        musicId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PkInfo)
    }

    static {
      defaultInstance = new PkInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PkInfo)
  }

  public interface RivalInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 rivalId = 1;
    /**
     * <code>required int32 rivalId = 1;</code>
     */
    boolean hasRivalId();
    /**
     * <code>required int32 rivalId = 1;</code>
     */
    int getRivalId();

    // required int32 roomId = 2;
    /**
     * <code>required int32 roomId = 2;</code>
     */
    boolean hasRoomId();
    /**
     * <code>required int32 roomId = 2;</code>
     */
    int getRoomId();

    // required string rivalName = 3;
    /**
     * <code>required string rivalName = 3;</code>
     */
    boolean hasRivalName();
    /**
     * <code>required string rivalName = 3;</code>
     */
    java.lang.String getRivalName();
    /**
     * <code>required string rivalName = 3;</code>
     */
    com.google.protobuf.ByteString
        getRivalNameBytes();

    // required int32 rivalHigeScore = 4;
    /**
     * <code>required int32 rivalHigeScore = 4;</code>
     */
    boolean hasRivalHigeScore();
    /**
     * <code>required int32 rivalHigeScore = 4;</code>
     */
    int getRivalHigeScore();
  }
  /**
   * Protobuf type {@code RivalInfo}
   */
  public static final class RivalInfo extends
      com.google.protobuf.GeneratedMessage
      implements RivalInfoOrBuilder {
    // Use RivalInfo.newBuilder() to construct.
    private RivalInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RivalInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RivalInfo defaultInstance;
    public static RivalInfo getDefaultInstance() {
      return defaultInstance;
    }

    public RivalInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RivalInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rivalId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roomId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              rivalName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              rivalHigeScore_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.PkMsg.internal_static_RivalInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.PkMsg.internal_static_RivalInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.PkMsg.RivalInfo.class, com.qingcity.proto.PkMsg.RivalInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<RivalInfo> PARSER =
        new com.google.protobuf.AbstractParser<RivalInfo>() {
      public RivalInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RivalInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RivalInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 rivalId = 1;
    public static final int RIVALID_FIELD_NUMBER = 1;
    private int rivalId_;
    /**
     * <code>required int32 rivalId = 1;</code>
     */
    public boolean hasRivalId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rivalId = 1;</code>
     */
    public int getRivalId() {
      return rivalId_;
    }

    // required int32 roomId = 2;
    public static final int ROOMID_FIELD_NUMBER = 2;
    private int roomId_;
    /**
     * <code>required int32 roomId = 2;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 roomId = 2;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    // required string rivalName = 3;
    public static final int RIVALNAME_FIELD_NUMBER = 3;
    private java.lang.Object rivalName_;
    /**
     * <code>required string rivalName = 3;</code>
     */
    public boolean hasRivalName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string rivalName = 3;</code>
     */
    public java.lang.String getRivalName() {
      java.lang.Object ref = rivalName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rivalName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rivalName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRivalNameBytes() {
      java.lang.Object ref = rivalName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rivalName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 rivalHigeScore = 4;
    public static final int RIVALHIGESCORE_FIELD_NUMBER = 4;
    private int rivalHigeScore_;
    /**
     * <code>required int32 rivalHigeScore = 4;</code>
     */
    public boolean hasRivalHigeScore() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 rivalHigeScore = 4;</code>
     */
    public int getRivalHigeScore() {
      return rivalHigeScore_;
    }

    private void initFields() {
      rivalId_ = 0;
      roomId_ = 0;
      rivalName_ = "";
      rivalHigeScore_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRivalId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRivalName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRivalHigeScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rivalId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, roomId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRivalNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, rivalHigeScore_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rivalId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roomId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRivalNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rivalHigeScore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.PkMsg.RivalInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.PkMsg.RivalInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.PkMsg.RivalInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RivalInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.PkMsg.RivalInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.PkMsg.internal_static_RivalInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.PkMsg.internal_static_RivalInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.PkMsg.RivalInfo.class, com.qingcity.proto.PkMsg.RivalInfo.Builder.class);
      }

      // Construct using com.qingcity.proto.PkMsg.RivalInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rivalId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rivalName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        rivalHigeScore_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.PkMsg.internal_static_RivalInfo_descriptor;
      }

      public com.qingcity.proto.PkMsg.RivalInfo getDefaultInstanceForType() {
        return com.qingcity.proto.PkMsg.RivalInfo.getDefaultInstance();
      }

      public com.qingcity.proto.PkMsg.RivalInfo build() {
        com.qingcity.proto.PkMsg.RivalInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.PkMsg.RivalInfo buildPartial() {
        com.qingcity.proto.PkMsg.RivalInfo result = new com.qingcity.proto.PkMsg.RivalInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rivalId_ = rivalId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roomId_ = roomId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rivalName_ = rivalName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rivalHigeScore_ = rivalHigeScore_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.PkMsg.RivalInfo) {
          return mergeFrom((com.qingcity.proto.PkMsg.RivalInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.PkMsg.RivalInfo other) {
        if (other == com.qingcity.proto.PkMsg.RivalInfo.getDefaultInstance()) return this;
        if (other.hasRivalId()) {
          setRivalId(other.getRivalId());
        }
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        if (other.hasRivalName()) {
          bitField0_ |= 0x00000004;
          rivalName_ = other.rivalName_;
          onChanged();
        }
        if (other.hasRivalHigeScore()) {
          setRivalHigeScore(other.getRivalHigeScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRivalId()) {
          
          return false;
        }
        if (!hasRoomId()) {
          
          return false;
        }
        if (!hasRivalName()) {
          
          return false;
        }
        if (!hasRivalHigeScore()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.PkMsg.RivalInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.PkMsg.RivalInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 rivalId = 1;
      private int rivalId_ ;
      /**
       * <code>required int32 rivalId = 1;</code>
       */
      public boolean hasRivalId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rivalId = 1;</code>
       */
      public int getRivalId() {
        return rivalId_;
      }
      /**
       * <code>required int32 rivalId = 1;</code>
       */
      public Builder setRivalId(int value) {
        bitField0_ |= 0x00000001;
        rivalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rivalId = 1;</code>
       */
      public Builder clearRivalId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rivalId_ = 0;
        onChanged();
        return this;
      }

      // required int32 roomId = 2;
      private int roomId_ ;
      /**
       * <code>required int32 roomId = 2;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 roomId = 2;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>required int32 roomId = 2;</code>
       */
      public Builder setRoomId(int value) {
        bitField0_ |= 0x00000002;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roomId = 2;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roomId_ = 0;
        onChanged();
        return this;
      }

      // required string rivalName = 3;
      private java.lang.Object rivalName_ = "";
      /**
       * <code>required string rivalName = 3;</code>
       */
      public boolean hasRivalName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string rivalName = 3;</code>
       */
      public java.lang.String getRivalName() {
        java.lang.Object ref = rivalName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rivalName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rivalName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRivalNameBytes() {
        java.lang.Object ref = rivalName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rivalName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rivalName = 3;</code>
       */
      public Builder setRivalName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        rivalName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rivalName = 3;</code>
       */
      public Builder clearRivalName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rivalName_ = getDefaultInstance().getRivalName();
        onChanged();
        return this;
      }
      /**
       * <code>required string rivalName = 3;</code>
       */
      public Builder setRivalNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        rivalName_ = value;
        onChanged();
        return this;
      }

      // required int32 rivalHigeScore = 4;
      private int rivalHigeScore_ ;
      /**
       * <code>required int32 rivalHigeScore = 4;</code>
       */
      public boolean hasRivalHigeScore() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 rivalHigeScore = 4;</code>
       */
      public int getRivalHigeScore() {
        return rivalHigeScore_;
      }
      /**
       * <code>required int32 rivalHigeScore = 4;</code>
       */
      public Builder setRivalHigeScore(int value) {
        bitField0_ |= 0x00000008;
        rivalHigeScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rivalHigeScore = 4;</code>
       */
      public Builder clearRivalHigeScore() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rivalHigeScore_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RivalInfo)
    }

    static {
      defaultInstance = new RivalInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RivalInfo)
  }

  public interface PkResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 playerId = 1;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int32 playerId = 1;</code>
     */
    int getPlayerId();

    // required int32 Grade = 2;
    /**
     * <code>required int32 Grade = 2;</code>
     */
    boolean hasGrade();
    /**
     * <code>required int32 Grade = 2;</code>
     */
    int getGrade();

    // required string isWinner = 3;
    /**
     * <code>required string isWinner = 3;</code>
     */
    boolean hasIsWinner();
    /**
     * <code>required string isWinner = 3;</code>
     */
    java.lang.String getIsWinner();
    /**
     * <code>required string isWinner = 3;</code>
     */
    com.google.protobuf.ByteString
        getIsWinnerBytes();

    // required int32 rewardGold = 4;
    /**
     * <code>required int32 rewardGold = 4;</code>
     */
    boolean hasRewardGold();
    /**
     * <code>required int32 rewardGold = 4;</code>
     */
    int getRewardGold();

    // required int32 rewardDiamond = 5;
    /**
     * <code>required int32 rewardDiamond = 5;</code>
     */
    boolean hasRewardDiamond();
    /**
     * <code>required int32 rewardDiamond = 5;</code>
     */
    int getRewardDiamond();
  }
  /**
   * Protobuf type {@code PkResult}
   */
  public static final class PkResult extends
      com.google.protobuf.GeneratedMessage
      implements PkResultOrBuilder {
    // Use PkResult.newBuilder() to construct.
    private PkResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PkResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PkResult defaultInstance;
    public static PkResult getDefaultInstance() {
      return defaultInstance;
    }

    public PkResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PkResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              grade_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              isWinner_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              rewardGold_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              rewardDiamond_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.PkMsg.internal_static_PkResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.PkMsg.internal_static_PkResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.PkMsg.PkResult.class, com.qingcity.proto.PkMsg.PkResult.Builder.class);
    }

    public static com.google.protobuf.Parser<PkResult> PARSER =
        new com.google.protobuf.AbstractParser<PkResult>() {
      public PkResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PkResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PkResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    // required int32 Grade = 2;
    public static final int GRADE_FIELD_NUMBER = 2;
    private int grade_;
    /**
     * <code>required int32 Grade = 2;</code>
     */
    public boolean hasGrade() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 Grade = 2;</code>
     */
    public int getGrade() {
      return grade_;
    }

    // required string isWinner = 3;
    public static final int ISWINNER_FIELD_NUMBER = 3;
    private java.lang.Object isWinner_;
    /**
     * <code>required string isWinner = 3;</code>
     */
    public boolean hasIsWinner() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string isWinner = 3;</code>
     */
    public java.lang.String getIsWinner() {
      java.lang.Object ref = isWinner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          isWinner_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string isWinner = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIsWinnerBytes() {
      java.lang.Object ref = isWinner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isWinner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 rewardGold = 4;
    public static final int REWARDGOLD_FIELD_NUMBER = 4;
    private int rewardGold_;
    /**
     * <code>required int32 rewardGold = 4;</code>
     */
    public boolean hasRewardGold() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 rewardGold = 4;</code>
     */
    public int getRewardGold() {
      return rewardGold_;
    }

    // required int32 rewardDiamond = 5;
    public static final int REWARDDIAMOND_FIELD_NUMBER = 5;
    private int rewardDiamond_;
    /**
     * <code>required int32 rewardDiamond = 5;</code>
     */
    public boolean hasRewardDiamond() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 rewardDiamond = 5;</code>
     */
    public int getRewardDiamond() {
      return rewardDiamond_;
    }

    private void initFields() {
      playerId_ = 0;
      grade_ = 0;
      isWinner_ = "";
      rewardGold_ = 0;
      rewardDiamond_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGrade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsWinner()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRewardGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRewardDiamond()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, grade_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIsWinnerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, rewardGold_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, rewardDiamond_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, grade_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIsWinnerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rewardGold_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, rewardDiamond_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.PkMsg.PkResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.PkMsg.PkResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.PkMsg.PkResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PkResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.PkMsg.PkResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.PkMsg.internal_static_PkResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.PkMsg.internal_static_PkResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.PkMsg.PkResult.class, com.qingcity.proto.PkMsg.PkResult.Builder.class);
      }

      // Construct using com.qingcity.proto.PkMsg.PkResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        grade_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isWinner_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        rewardGold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        rewardDiamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.PkMsg.internal_static_PkResult_descriptor;
      }

      public com.qingcity.proto.PkMsg.PkResult getDefaultInstanceForType() {
        return com.qingcity.proto.PkMsg.PkResult.getDefaultInstance();
      }

      public com.qingcity.proto.PkMsg.PkResult build() {
        com.qingcity.proto.PkMsg.PkResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.PkMsg.PkResult buildPartial() {
        com.qingcity.proto.PkMsg.PkResult result = new com.qingcity.proto.PkMsg.PkResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.grade_ = grade_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isWinner_ = isWinner_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rewardGold_ = rewardGold_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.rewardDiamond_ = rewardDiamond_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.PkMsg.PkResult) {
          return mergeFrom((com.qingcity.proto.PkMsg.PkResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.PkMsg.PkResult other) {
        if (other == com.qingcity.proto.PkMsg.PkResult.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasGrade()) {
          setGrade(other.getGrade());
        }
        if (other.hasIsWinner()) {
          bitField0_ |= 0x00000004;
          isWinner_ = other.isWinner_;
          onChanged();
        }
        if (other.hasRewardGold()) {
          setRewardGold(other.getRewardGold());
        }
        if (other.hasRewardDiamond()) {
          setRewardDiamond(other.getRewardDiamond());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasGrade()) {
          
          return false;
        }
        if (!hasIsWinner()) {
          
          return false;
        }
        if (!hasRewardGold()) {
          
          return false;
        }
        if (!hasRewardDiamond()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.PkMsg.PkResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.PkMsg.PkResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 playerId = 1;
      private int playerId_ ;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // required int32 Grade = 2;
      private int grade_ ;
      /**
       * <code>required int32 Grade = 2;</code>
       */
      public boolean hasGrade() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 Grade = 2;</code>
       */
      public int getGrade() {
        return grade_;
      }
      /**
       * <code>required int32 Grade = 2;</code>
       */
      public Builder setGrade(int value) {
        bitField0_ |= 0x00000002;
        grade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Grade = 2;</code>
       */
      public Builder clearGrade() {
        bitField0_ = (bitField0_ & ~0x00000002);
        grade_ = 0;
        onChanged();
        return this;
      }

      // required string isWinner = 3;
      private java.lang.Object isWinner_ = "";
      /**
       * <code>required string isWinner = 3;</code>
       */
      public boolean hasIsWinner() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string isWinner = 3;</code>
       */
      public java.lang.String getIsWinner() {
        java.lang.Object ref = isWinner_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          isWinner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string isWinner = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIsWinnerBytes() {
        java.lang.Object ref = isWinner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isWinner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string isWinner = 3;</code>
       */
      public Builder setIsWinner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        isWinner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string isWinner = 3;</code>
       */
      public Builder clearIsWinner() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isWinner_ = getDefaultInstance().getIsWinner();
        onChanged();
        return this;
      }
      /**
       * <code>required string isWinner = 3;</code>
       */
      public Builder setIsWinnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        isWinner_ = value;
        onChanged();
        return this;
      }

      // required int32 rewardGold = 4;
      private int rewardGold_ ;
      /**
       * <code>required int32 rewardGold = 4;</code>
       */
      public boolean hasRewardGold() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 rewardGold = 4;</code>
       */
      public int getRewardGold() {
        return rewardGold_;
      }
      /**
       * <code>required int32 rewardGold = 4;</code>
       */
      public Builder setRewardGold(int value) {
        bitField0_ |= 0x00000008;
        rewardGold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rewardGold = 4;</code>
       */
      public Builder clearRewardGold() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rewardGold_ = 0;
        onChanged();
        return this;
      }

      // required int32 rewardDiamond = 5;
      private int rewardDiamond_ ;
      /**
       * <code>required int32 rewardDiamond = 5;</code>
       */
      public boolean hasRewardDiamond() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 rewardDiamond = 5;</code>
       */
      public int getRewardDiamond() {
        return rewardDiamond_;
      }
      /**
       * <code>required int32 rewardDiamond = 5;</code>
       */
      public Builder setRewardDiamond(int value) {
        bitField0_ |= 0x00000010;
        rewardDiamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rewardDiamond = 5;</code>
       */
      public Builder clearRewardDiamond() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rewardDiamond_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PkResult)
    }

    static {
      defaultInstance = new PkResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PkResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PkInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PkInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RivalInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RivalInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PkResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PkResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010pk.proto\"+\n\006PkInfo\022\020\n\010playerId\030\001 \002(\005\022\017" +
      "\n\007musicId\030\002 \002(\005\"W\n\tRivalInfo\022\017\n\007rivalId\030" +
      "\001 \002(\005\022\016\n\006roomId\030\002 \002(\005\022\021\n\trivalName\030\003 \002(\t" +
      "\022\026\n\016rivalHigeScore\030\004 \002(\005\"h\n\010PkResult\022\020\n\010" +
      "playerId\030\001 \002(\005\022\r\n\005Grade\030\002 \002(\005\022\020\n\010isWinne" +
      "r\030\003 \002(\t\022\022\n\nrewardGold\030\004 \002(\005\022\025\n\rrewardDia" +
      "mond\030\005 \002(\005B\033\n\022com.qingcity.protoB\005PkMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PkInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PkInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PkInfo_descriptor,
              new java.lang.String[] { "PlayerId", "MusicId", });
          internal_static_RivalInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RivalInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RivalInfo_descriptor,
              new java.lang.String[] { "RivalId", "RoomId", "RivalName", "RivalHigeScore", });
          internal_static_PkResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PkResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PkResult_descriptor,
              new java.lang.String[] { "PlayerId", "Grade", "IsWinner", "RewardGold", "RewardDiamond", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
