// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package com.qingcity.proto;

public final class Player {
  private Player() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface getInfoRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userId = 1;
    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();
  }
  /**
   * Protobuf type {@code getInfoRequest}
   */
  public static final class getInfoRequest extends
      com.google.protobuf.GeneratedMessage
      implements getInfoRequestOrBuilder {
    // Use getInfoRequest.newBuilder() to construct.
    private getInfoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private getInfoRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final getInfoRequest defaultInstance;
    public static getInfoRequest getDefaultInstance() {
      return defaultInstance;
    }

    public getInfoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private getInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.Player.internal_static_getInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.Player.internal_static_getInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.Player.getInfoRequest.class, com.qingcity.proto.Player.getInfoRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<getInfoRequest> PARSER =
        new com.google.protobuf.AbstractParser<getInfoRequest>() {
      public getInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getInfoRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<getInfoRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    private void initFields() {
      userId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.Player.getInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.Player.getInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.Player.getInfoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.Player.getInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.Player.internal_static_getInfoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.Player.internal_static_getInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.Player.getInfoRequest.class, com.qingcity.proto.Player.getInfoRequest.Builder.class);
      }

      // Construct using com.qingcity.proto.Player.getInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.Player.internal_static_getInfoRequest_descriptor;
      }

      public com.qingcity.proto.Player.getInfoRequest getDefaultInstanceForType() {
        return com.qingcity.proto.Player.getInfoRequest.getDefaultInstance();
      }

      public com.qingcity.proto.Player.getInfoRequest build() {
        com.qingcity.proto.Player.getInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.Player.getInfoRequest buildPartial() {
        com.qingcity.proto.Player.getInfoRequest result = new com.qingcity.proto.Player.getInfoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.Player.getInfoRequest) {
          return mergeFrom((com.qingcity.proto.Player.getInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.Player.getInfoRequest other) {
        if (other == com.qingcity.proto.Player.getInfoRequest.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.Player.getInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.Player.getInfoRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userId = 1;
      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:getInfoRequest)
    }

    static {
      defaultInstance = new getInfoRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:getInfoRequest)
  }

  public interface PlayerInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 userId = 1;
    /**
     * <code>optional int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 userId = 1;</code>
     */
    int getUserId();

    // optional int32 level = 2;
    /**
     * <code>optional int32 level = 2;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 2;</code>
     */
    int getLevel();

    // optional int32 experience = 3;
    /**
     * <code>optional int32 experience = 3;</code>
     */
    boolean hasExperience();
    /**
     * <code>optional int32 experience = 3;</code>
     */
    int getExperience();

    // optional int32 power = 4;
    /**
     * <code>optional int32 power = 4;</code>
     */
    boolean hasPower();
    /**
     * <code>optional int32 power = 4;</code>
     */
    int getPower();

    // optional int32 diamond = 5;
    /**
     * <code>optional int32 diamond = 5;</code>
     */
    boolean hasDiamond();
    /**
     * <code>optional int32 diamond = 5;</code>
     */
    int getDiamond();

    // optional int32 gold = 6;
    /**
     * <code>optional int32 gold = 6;</code>
     */
    boolean hasGold();
    /**
     * <code>optional int32 gold = 6;</code>
     */
    int getGold();

    // optional int32 societyId = 7;
    /**
     * <code>optional int32 societyId = 7;</code>
     */
    boolean hasSocietyId();
    /**
     * <code>optional int32 societyId = 7;</code>
     */
    int getSocietyId();

    // optional int32 contribution = 8;
    /**
     * <code>optional int32 contribution = 8;</code>
     */
    boolean hasContribution();
    /**
     * <code>optional int32 contribution = 8;</code>
     */
    int getContribution();

    // optional int32 job = 9;
    /**
     * <code>optional int32 job = 9;</code>
     */
    boolean hasJob();
    /**
     * <code>optional int32 job = 9;</code>
     */
    int getJob();

    // optional int32 nickname = 10;
    /**
     * <code>optional int32 nickname = 10;</code>
     */
    boolean hasNickname();
    /**
     * <code>optional int32 nickname = 10;</code>
     */
    int getNickname();
  }
  /**
   * Protobuf type {@code PlayerInfo}
   */
  public static final class PlayerInfo extends
      com.google.protobuf.GeneratedMessage
      implements PlayerInfoOrBuilder {
    // Use PlayerInfo.newBuilder() to construct.
    private PlayerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerInfo defaultInstance;
    public static PlayerInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              level_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              experience_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              power_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              diamond_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              gold_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              societyId_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              contribution_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              job_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              nickname_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.Player.internal_static_PlayerInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.Player.internal_static_PlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.Player.PlayerInfo.class, com.qingcity.proto.Player.PlayerInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerInfo> PARSER =
        new com.google.protobuf.AbstractParser<PlayerInfo>() {
      public PlayerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional int32 level = 2;
    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    /**
     * <code>optional int32 level = 2;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 level = 2;</code>
     */
    public int getLevel() {
      return level_;
    }

    // optional int32 experience = 3;
    public static final int EXPERIENCE_FIELD_NUMBER = 3;
    private int experience_;
    /**
     * <code>optional int32 experience = 3;</code>
     */
    public boolean hasExperience() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 experience = 3;</code>
     */
    public int getExperience() {
      return experience_;
    }

    // optional int32 power = 4;
    public static final int POWER_FIELD_NUMBER = 4;
    private int power_;
    /**
     * <code>optional int32 power = 4;</code>
     */
    public boolean hasPower() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 power = 4;</code>
     */
    public int getPower() {
      return power_;
    }

    // optional int32 diamond = 5;
    public static final int DIAMOND_FIELD_NUMBER = 5;
    private int diamond_;
    /**
     * <code>optional int32 diamond = 5;</code>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 diamond = 5;</code>
     */
    public int getDiamond() {
      return diamond_;
    }

    // optional int32 gold = 6;
    public static final int GOLD_FIELD_NUMBER = 6;
    private int gold_;
    /**
     * <code>optional int32 gold = 6;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 gold = 6;</code>
     */
    public int getGold() {
      return gold_;
    }

    // optional int32 societyId = 7;
    public static final int SOCIETYID_FIELD_NUMBER = 7;
    private int societyId_;
    /**
     * <code>optional int32 societyId = 7;</code>
     */
    public boolean hasSocietyId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 societyId = 7;</code>
     */
    public int getSocietyId() {
      return societyId_;
    }

    // optional int32 contribution = 8;
    public static final int CONTRIBUTION_FIELD_NUMBER = 8;
    private int contribution_;
    /**
     * <code>optional int32 contribution = 8;</code>
     */
    public boolean hasContribution() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 contribution = 8;</code>
     */
    public int getContribution() {
      return contribution_;
    }

    // optional int32 job = 9;
    public static final int JOB_FIELD_NUMBER = 9;
    private int job_;
    /**
     * <code>optional int32 job = 9;</code>
     */
    public boolean hasJob() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 job = 9;</code>
     */
    public int getJob() {
      return job_;
    }

    // optional int32 nickname = 10;
    public static final int NICKNAME_FIELD_NUMBER = 10;
    private int nickname_;
    /**
     * <code>optional int32 nickname = 10;</code>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 nickname = 10;</code>
     */
    public int getNickname() {
      return nickname_;
    }

    private void initFields() {
      userId_ = 0;
      level_ = 0;
      experience_ = 0;
      power_ = 0;
      diamond_ = 0;
      gold_ = 0;
      societyId_ = 0;
      contribution_ = 0;
      job_ = 0;
      nickname_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, level_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, experience_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, power_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, diamond_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, gold_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, societyId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, contribution_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, job_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, nickname_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, experience_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, power_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, diamond_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, gold_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, societyId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, contribution_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, job_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, nickname_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.Player.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.Player.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.Player.PlayerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.Player.PlayerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.Player.internal_static_PlayerInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.Player.internal_static_PlayerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.Player.PlayerInfo.class, com.qingcity.proto.Player.PlayerInfo.Builder.class);
      }

      // Construct using com.qingcity.proto.Player.PlayerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        experience_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        power_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        diamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        societyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        contribution_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        job_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        nickname_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.Player.internal_static_PlayerInfo_descriptor;
      }

      public com.qingcity.proto.Player.PlayerInfo getDefaultInstanceForType() {
        return com.qingcity.proto.Player.PlayerInfo.getDefaultInstance();
      }

      public com.qingcity.proto.Player.PlayerInfo build() {
        com.qingcity.proto.Player.PlayerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.Player.PlayerInfo buildPartial() {
        com.qingcity.proto.Player.PlayerInfo result = new com.qingcity.proto.Player.PlayerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.experience_ = experience_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.power_ = power_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.diamond_ = diamond_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.societyId_ = societyId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.contribution_ = contribution_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.job_ = job_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.nickname_ = nickname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.Player.PlayerInfo) {
          return mergeFrom((com.qingcity.proto.Player.PlayerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.Player.PlayerInfo other) {
        if (other == com.qingcity.proto.Player.PlayerInfo.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasExperience()) {
          setExperience(other.getExperience());
        }
        if (other.hasPower()) {
          setPower(other.getPower());
        }
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasSocietyId()) {
          setSocietyId(other.getSocietyId());
        }
        if (other.hasContribution()) {
          setContribution(other.getContribution());
        }
        if (other.hasJob()) {
          setJob(other.getJob());
        }
        if (other.hasNickname()) {
          setNickname(other.getNickname());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.Player.PlayerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.Player.PlayerInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 userId = 1;
      private int userId_ ;
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 level = 2;
      private int level_ ;
      /**
       * <code>optional int32 level = 2;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 level = 2;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 2;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 2;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        onChanged();
        return this;
      }

      // optional int32 experience = 3;
      private int experience_ ;
      /**
       * <code>optional int32 experience = 3;</code>
       */
      public boolean hasExperience() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 experience = 3;</code>
       */
      public int getExperience() {
        return experience_;
      }
      /**
       * <code>optional int32 experience = 3;</code>
       */
      public Builder setExperience(int value) {
        bitField0_ |= 0x00000004;
        experience_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 experience = 3;</code>
       */
      public Builder clearExperience() {
        bitField0_ = (bitField0_ & ~0x00000004);
        experience_ = 0;
        onChanged();
        return this;
      }

      // optional int32 power = 4;
      private int power_ ;
      /**
       * <code>optional int32 power = 4;</code>
       */
      public boolean hasPower() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 power = 4;</code>
       */
      public int getPower() {
        return power_;
      }
      /**
       * <code>optional int32 power = 4;</code>
       */
      public Builder setPower(int value) {
        bitField0_ |= 0x00000008;
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 power = 4;</code>
       */
      public Builder clearPower() {
        bitField0_ = (bitField0_ & ~0x00000008);
        power_ = 0;
        onChanged();
        return this;
      }

      // optional int32 diamond = 5;
      private int diamond_ ;
      /**
       * <code>optional int32 diamond = 5;</code>
       */
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 diamond = 5;</code>
       */
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <code>optional int32 diamond = 5;</code>
       */
      public Builder setDiamond(int value) {
        bitField0_ |= 0x00000010;
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 diamond = 5;</code>
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000010);
        diamond_ = 0;
        onChanged();
        return this;
      }

      // optional int32 gold = 6;
      private int gold_ ;
      /**
       * <code>optional int32 gold = 6;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 gold = 6;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>optional int32 gold = 6;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000020;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gold = 6;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000020);
        gold_ = 0;
        onChanged();
        return this;
      }

      // optional int32 societyId = 7;
      private int societyId_ ;
      /**
       * <code>optional int32 societyId = 7;</code>
       */
      public boolean hasSocietyId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 societyId = 7;</code>
       */
      public int getSocietyId() {
        return societyId_;
      }
      /**
       * <code>optional int32 societyId = 7;</code>
       */
      public Builder setSocietyId(int value) {
        bitField0_ |= 0x00000040;
        societyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 societyId = 7;</code>
       */
      public Builder clearSocietyId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        societyId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 contribution = 8;
      private int contribution_ ;
      /**
       * <code>optional int32 contribution = 8;</code>
       */
      public boolean hasContribution() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 contribution = 8;</code>
       */
      public int getContribution() {
        return contribution_;
      }
      /**
       * <code>optional int32 contribution = 8;</code>
       */
      public Builder setContribution(int value) {
        bitField0_ |= 0x00000080;
        contribution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contribution = 8;</code>
       */
      public Builder clearContribution() {
        bitField0_ = (bitField0_ & ~0x00000080);
        contribution_ = 0;
        onChanged();
        return this;
      }

      // optional int32 job = 9;
      private int job_ ;
      /**
       * <code>optional int32 job = 9;</code>
       */
      public boolean hasJob() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 job = 9;</code>
       */
      public int getJob() {
        return job_;
      }
      /**
       * <code>optional int32 job = 9;</code>
       */
      public Builder setJob(int value) {
        bitField0_ |= 0x00000100;
        job_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 job = 9;</code>
       */
      public Builder clearJob() {
        bitField0_ = (bitField0_ & ~0x00000100);
        job_ = 0;
        onChanged();
        return this;
      }

      // optional int32 nickname = 10;
      private int nickname_ ;
      /**
       * <code>optional int32 nickname = 10;</code>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 nickname = 10;</code>
       */
      public int getNickname() {
        return nickname_;
      }
      /**
       * <code>optional int32 nickname = 10;</code>
       */
      public Builder setNickname(int value) {
        bitField0_ |= 0x00000200;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 nickname = 10;</code>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000200);
        nickname_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerInfo)
    }

    static {
      defaultInstance = new PlayerInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerInfo)
  }

  public interface updateRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userId = 1;
    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();

    // optional int32 power = 2;
    /**
     * <code>optional int32 power = 2;</code>
     */
    boolean hasPower();
    /**
     * <code>optional int32 power = 2;</code>
     */
    int getPower();

    // optional int32 diamond = 3;
    /**
     * <code>optional int32 diamond = 3;</code>
     */
    boolean hasDiamond();
    /**
     * <code>optional int32 diamond = 3;</code>
     */
    int getDiamond();

    // optional int32 gold = 4;
    /**
     * <code>optional int32 gold = 4;</code>
     */
    boolean hasGold();
    /**
     * <code>optional int32 gold = 4;</code>
     */
    int getGold();
  }
  /**
   * Protobuf type {@code updateRequest}
   */
  public static final class updateRequest extends
      com.google.protobuf.GeneratedMessage
      implements updateRequestOrBuilder {
    // Use updateRequest.newBuilder() to construct.
    private updateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private updateRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final updateRequest defaultInstance;
    public static updateRequest getDefaultInstance() {
      return defaultInstance;
    }

    public updateRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private updateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              power_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              diamond_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gold_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.Player.internal_static_updateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.Player.internal_static_updateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.Player.updateRequest.class, com.qingcity.proto.Player.updateRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<updateRequest> PARSER =
        new com.google.protobuf.AbstractParser<updateRequest>() {
      public updateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new updateRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<updateRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional int32 power = 2;
    public static final int POWER_FIELD_NUMBER = 2;
    private int power_;
    /**
     * <code>optional int32 power = 2;</code>
     */
    public boolean hasPower() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 power = 2;</code>
     */
    public int getPower() {
      return power_;
    }

    // optional int32 diamond = 3;
    public static final int DIAMOND_FIELD_NUMBER = 3;
    private int diamond_;
    /**
     * <code>optional int32 diamond = 3;</code>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 diamond = 3;</code>
     */
    public int getDiamond() {
      return diamond_;
    }

    // optional int32 gold = 4;
    public static final int GOLD_FIELD_NUMBER = 4;
    private int gold_;
    /**
     * <code>optional int32 gold = 4;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 gold = 4;</code>
     */
    public int getGold() {
      return gold_;
    }

    private void initFields() {
      userId_ = 0;
      power_ = 0;
      diamond_ = 0;
      gold_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, power_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, diamond_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, gold_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, power_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, diamond_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gold_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.Player.updateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.Player.updateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.Player.updateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.Player.updateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.Player.updateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.Player.updateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.Player.updateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.Player.updateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.Player.updateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.Player.updateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.Player.updateRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code updateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.Player.updateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.Player.internal_static_updateRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.Player.internal_static_updateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.Player.updateRequest.class, com.qingcity.proto.Player.updateRequest.Builder.class);
      }

      // Construct using com.qingcity.proto.Player.updateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        power_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        diamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.Player.internal_static_updateRequest_descriptor;
      }

      public com.qingcity.proto.Player.updateRequest getDefaultInstanceForType() {
        return com.qingcity.proto.Player.updateRequest.getDefaultInstance();
      }

      public com.qingcity.proto.Player.updateRequest build() {
        com.qingcity.proto.Player.updateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.Player.updateRequest buildPartial() {
        com.qingcity.proto.Player.updateRequest result = new com.qingcity.proto.Player.updateRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.power_ = power_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.diamond_ = diamond_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gold_ = gold_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.Player.updateRequest) {
          return mergeFrom((com.qingcity.proto.Player.updateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.Player.updateRequest other) {
        if (other == com.qingcity.proto.Player.updateRequest.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasPower()) {
          setPower(other.getPower());
        }
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.Player.updateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.Player.updateRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userId = 1;
      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 power = 2;
      private int power_ ;
      /**
       * <code>optional int32 power = 2;</code>
       */
      public boolean hasPower() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 power = 2;</code>
       */
      public int getPower() {
        return power_;
      }
      /**
       * <code>optional int32 power = 2;</code>
       */
      public Builder setPower(int value) {
        bitField0_ |= 0x00000002;
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 power = 2;</code>
       */
      public Builder clearPower() {
        bitField0_ = (bitField0_ & ~0x00000002);
        power_ = 0;
        onChanged();
        return this;
      }

      // optional int32 diamond = 3;
      private int diamond_ ;
      /**
       * <code>optional int32 diamond = 3;</code>
       */
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 diamond = 3;</code>
       */
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <code>optional int32 diamond = 3;</code>
       */
      public Builder setDiamond(int value) {
        bitField0_ |= 0x00000004;
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 diamond = 3;</code>
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000004);
        diamond_ = 0;
        onChanged();
        return this;
      }

      // optional int32 gold = 4;
      private int gold_ ;
      /**
       * <code>optional int32 gold = 4;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 gold = 4;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>optional int32 gold = 4;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000008;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gold = 4;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gold_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:updateRequest)
    }

    static {
      defaultInstance = new updateRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:updateRequest)
  }

  public interface udpateResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userId = 1;
    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();

    // optional int32 power = 2;
    /**
     * <code>optional int32 power = 2;</code>
     */
    boolean hasPower();
    /**
     * <code>optional int32 power = 2;</code>
     */
    int getPower();

    // optional int32 diamond = 3;
    /**
     * <code>optional int32 diamond = 3;</code>
     */
    boolean hasDiamond();
    /**
     * <code>optional int32 diamond = 3;</code>
     */
    int getDiamond();

    // optional int32 gold = 4;
    /**
     * <code>optional int32 gold = 4;</code>
     */
    boolean hasGold();
    /**
     * <code>optional int32 gold = 4;</code>
     */
    int getGold();
  }
  /**
   * Protobuf type {@code udpateResponse}
   */
  public static final class udpateResponse extends
      com.google.protobuf.GeneratedMessage
      implements udpateResponseOrBuilder {
    // Use udpateResponse.newBuilder() to construct.
    private udpateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private udpateResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final udpateResponse defaultInstance;
    public static udpateResponse getDefaultInstance() {
      return defaultInstance;
    }

    public udpateResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private udpateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              power_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              diamond_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gold_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.Player.internal_static_udpateResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.Player.internal_static_udpateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.Player.udpateResponse.class, com.qingcity.proto.Player.udpateResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<udpateResponse> PARSER =
        new com.google.protobuf.AbstractParser<udpateResponse>() {
      public udpateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new udpateResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<udpateResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional int32 power = 2;
    public static final int POWER_FIELD_NUMBER = 2;
    private int power_;
    /**
     * <code>optional int32 power = 2;</code>
     */
    public boolean hasPower() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 power = 2;</code>
     */
    public int getPower() {
      return power_;
    }

    // optional int32 diamond = 3;
    public static final int DIAMOND_FIELD_NUMBER = 3;
    private int diamond_;
    /**
     * <code>optional int32 diamond = 3;</code>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 diamond = 3;</code>
     */
    public int getDiamond() {
      return diamond_;
    }

    // optional int32 gold = 4;
    public static final int GOLD_FIELD_NUMBER = 4;
    private int gold_;
    /**
     * <code>optional int32 gold = 4;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 gold = 4;</code>
     */
    public int getGold() {
      return gold_;
    }

    private void initFields() {
      userId_ = 0;
      power_ = 0;
      diamond_ = 0;
      gold_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, power_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, diamond_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, gold_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, power_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, diamond_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gold_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.Player.udpateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.Player.udpateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.Player.udpateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.Player.udpateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.Player.udpateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.Player.udpateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.Player.udpateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.Player.udpateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.Player.udpateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.Player.udpateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.Player.udpateResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code udpateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.Player.udpateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.Player.internal_static_udpateResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.Player.internal_static_udpateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.Player.udpateResponse.class, com.qingcity.proto.Player.udpateResponse.Builder.class);
      }

      // Construct using com.qingcity.proto.Player.udpateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        power_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        diamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.Player.internal_static_udpateResponse_descriptor;
      }

      public com.qingcity.proto.Player.udpateResponse getDefaultInstanceForType() {
        return com.qingcity.proto.Player.udpateResponse.getDefaultInstance();
      }

      public com.qingcity.proto.Player.udpateResponse build() {
        com.qingcity.proto.Player.udpateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.Player.udpateResponse buildPartial() {
        com.qingcity.proto.Player.udpateResponse result = new com.qingcity.proto.Player.udpateResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.power_ = power_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.diamond_ = diamond_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gold_ = gold_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.Player.udpateResponse) {
          return mergeFrom((com.qingcity.proto.Player.udpateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.Player.udpateResponse other) {
        if (other == com.qingcity.proto.Player.udpateResponse.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasPower()) {
          setPower(other.getPower());
        }
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.Player.udpateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.Player.udpateResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userId = 1;
      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 power = 2;
      private int power_ ;
      /**
       * <code>optional int32 power = 2;</code>
       */
      public boolean hasPower() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 power = 2;</code>
       */
      public int getPower() {
        return power_;
      }
      /**
       * <code>optional int32 power = 2;</code>
       */
      public Builder setPower(int value) {
        bitField0_ |= 0x00000002;
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 power = 2;</code>
       */
      public Builder clearPower() {
        bitField0_ = (bitField0_ & ~0x00000002);
        power_ = 0;
        onChanged();
        return this;
      }

      // optional int32 diamond = 3;
      private int diamond_ ;
      /**
       * <code>optional int32 diamond = 3;</code>
       */
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 diamond = 3;</code>
       */
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <code>optional int32 diamond = 3;</code>
       */
      public Builder setDiamond(int value) {
        bitField0_ |= 0x00000004;
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 diamond = 3;</code>
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000004);
        diamond_ = 0;
        onChanged();
        return this;
      }

      // optional int32 gold = 4;
      private int gold_ ;
      /**
       * <code>optional int32 gold = 4;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 gold = 4;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>optional int32 gold = 4;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000008;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gold = 4;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gold_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:udpateResponse)
    }

    static {
      defaultInstance = new udpateResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:udpateResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_getInfoRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_getInfoRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_updateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_updateRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_udpateResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_udpateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014player.proto\" \n\016getInfoRequest\022\016\n\006user" +
      "Id\030\001 \002(\005\"\265\001\n\nPlayerInfo\022\016\n\006userId\030\001 \001(\005\022" +
      "\r\n\005level\030\002 \001(\005\022\022\n\nexperience\030\003 \001(\005\022\r\n\005po" +
      "wer\030\004 \001(\005\022\017\n\007diamond\030\005 \001(\005\022\014\n\004gold\030\006 \001(\005" +
      "\022\021\n\tsocietyId\030\007 \001(\005\022\024\n\014contribution\030\010 \001(" +
      "\005\022\013\n\003job\030\t \001(\005\022\020\n\010nickname\030\n \001(\005\"M\n\rupda" +
      "teRequest\022\016\n\006userId\030\001 \002(\005\022\r\n\005power\030\002 \001(\005" +
      "\022\017\n\007diamond\030\003 \001(\005\022\014\n\004gold\030\004 \001(\005\"N\n\016udpat" +
      "eResponse\022\016\n\006userId\030\001 \002(\005\022\r\n\005power\030\002 \001(\005" +
      "\022\017\n\007diamond\030\003 \001(\005\022\014\n\004gold\030\004 \001(\005B\034\n\022com.q",
      "ingcity.protoB\006Player"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_getInfoRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_getInfoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_getInfoRequest_descriptor,
              new java.lang.String[] { "UserId", });
          internal_static_PlayerInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PlayerInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerInfo_descriptor,
              new java.lang.String[] { "UserId", "Level", "Experience", "Power", "Diamond", "Gold", "SocietyId", "Contribution", "Job", "Nickname", });
          internal_static_updateRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_updateRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_updateRequest_descriptor,
              new java.lang.String[] { "UserId", "Power", "Diamond", "Gold", });
          internal_static_udpateResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_udpateResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_udpateResponse_descriptor,
              new java.lang.String[] { "UserId", "Power", "Diamond", "Gold", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
