// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.qingcity.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 uId = 1;
    /**
     * <code>optional uint32 uId = 1;</code>
     */
    boolean hasUId();
    /**
     * <code>optional uint32 uId = 1;</code>
     */
    int getUId();

    // optional string uName = 2;
    /**
     * <code>optional string uName = 2;</code>
     */
    boolean hasUName();
    /**
     * <code>optional string uName = 2;</code>
     */
    java.lang.String getUName();
    /**
     * <code>optional string uName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUNameBytes();

    // optional string uPassword = 3;
    /**
     * <code>optional string uPassword = 3;</code>
     */
    boolean hasUPassword();
    /**
     * <code>optional string uPassword = 3;</code>
     */
    java.lang.String getUPassword();
    /**
     * <code>optional string uPassword = 3;</code>
     */
    com.google.protobuf.ByteString
        getUPasswordBytes();

    // optional uint32 uPower = 4;
    /**
     * <code>optional uint32 uPower = 4;</code>
     */
    boolean hasUPower();
    /**
     * <code>optional uint32 uPower = 4;</code>
     */
    int getUPower();

    // optional uint32 uGold = 5;
    /**
     * <code>optional uint32 uGold = 5;</code>
     */
    boolean hasUGold();
    /**
     * <code>optional uint32 uGold = 5;</code>
     */
    int getUGold();

    // optional uint32 uDiamond = 6;
    /**
     * <code>optional uint32 uDiamond = 6;</code>
     */
    boolean hasUDiamond();
    /**
     * <code>optional uint32 uDiamond = 6;</code>
     */
    int getUDiamond();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uId_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              uName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              uPassword_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              uPower_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              uGold_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              uDiamond_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.UserProto.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.UserProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.UserProto.User.class, com.qingcity.proto.UserProto.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 uId = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private int uId_;
    /**
     * <code>optional uint32 uId = 1;</code>
     */
    public boolean hasUId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 uId = 1;</code>
     */
    public int getUId() {
      return uId_;
    }

    // optional string uName = 2;
    public static final int UNAME_FIELD_NUMBER = 2;
    private java.lang.Object uName_;
    /**
     * <code>optional string uName = 2;</code>
     */
    public boolean hasUName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string uName = 2;</code>
     */
    public java.lang.String getUName() {
      java.lang.Object ref = uName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUNameBytes() {
      java.lang.Object ref = uName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string uPassword = 3;
    public static final int UPASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object uPassword_;
    /**
     * <code>optional string uPassword = 3;</code>
     */
    public boolean hasUPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string uPassword = 3;</code>
     */
    public java.lang.String getUPassword() {
      java.lang.Object ref = uPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uPassword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uPassword = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUPasswordBytes() {
      java.lang.Object ref = uPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 uPower = 4;
    public static final int UPOWER_FIELD_NUMBER = 4;
    private int uPower_;
    /**
     * <code>optional uint32 uPower = 4;</code>
     */
    public boolean hasUPower() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 uPower = 4;</code>
     */
    public int getUPower() {
      return uPower_;
    }

    // optional uint32 uGold = 5;
    public static final int UGOLD_FIELD_NUMBER = 5;
    private int uGold_;
    /**
     * <code>optional uint32 uGold = 5;</code>
     */
    public boolean hasUGold() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 uGold = 5;</code>
     */
    public int getUGold() {
      return uGold_;
    }

    // optional uint32 uDiamond = 6;
    public static final int UDIAMOND_FIELD_NUMBER = 6;
    private int uDiamond_;
    /**
     * <code>optional uint32 uDiamond = 6;</code>
     */
    public boolean hasUDiamond() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 uDiamond = 6;</code>
     */
    public int getUDiamond() {
      return uDiamond_;
    }

    private void initFields() {
      uId_ = 0;
      uName_ = "";
      uPassword_ = "";
      uPower_ = 0;
      uGold_ = 0;
      uDiamond_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, uId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, uPower_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, uGold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, uDiamond_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, uId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, uPower_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, uGold_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, uDiamond_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.UserProto.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.UserProto.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.UserProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.UserProto.User.class, com.qingcity.proto.UserProto.User.Builder.class);
      }

      // Construct using cpgame.demo.proto.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        uPassword_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        uPower_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        uGold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        uDiamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.UserProto.internal_static_User_descriptor;
      }

      public com.qingcity.proto.UserProto.User getDefaultInstanceForType() {
        return com.qingcity.proto.UserProto.User.getDefaultInstance();
      }

      public com.qingcity.proto.UserProto.User build() {
        com.qingcity.proto.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.UserProto.User buildPartial() {
        com.qingcity.proto.UserProto.User result = new com.qingcity.proto.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uId_ = uId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uName_ = uName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uPassword_ = uPassword_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uPower_ = uPower_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uGold_ = uGold_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.uDiamond_ = uDiamond_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.UserProto.User) {
          return mergeFrom((com.qingcity.proto.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.UserProto.User other) {
        if (other == com.qingcity.proto.UserProto.User.getDefaultInstance()) return this;
        if (other.hasUId()) {
          setUId(other.getUId());
        }
        if (other.hasUName()) {
          bitField0_ |= 0x00000002;
          uName_ = other.uName_;
          onChanged();
        }
        if (other.hasUPassword()) {
          bitField0_ |= 0x00000004;
          uPassword_ = other.uPassword_;
          onChanged();
        }
        if (other.hasUPower()) {
          setUPower(other.getUPower());
        }
        if (other.hasUGold()) {
          setUGold(other.getUGold());
        }
        if (other.hasUDiamond()) {
          setUDiamond(other.getUDiamond());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.UserProto.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 uId = 1;
      private int uId_ ;
      /**
       * <code>optional uint32 uId = 1;</code>
       */
      public boolean hasUId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 uId = 1;</code>
       */
      public int getUId() {
        return uId_;
      }
      /**
       * <code>optional uint32 uId = 1;</code>
       */
      public Builder setUId(int value) {
        bitField0_ |= 0x00000001;
        uId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uId = 1;</code>
       */
      public Builder clearUId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uId_ = 0;
        onChanged();
        return this;
      }

      // optional string uName = 2;
      private java.lang.Object uName_ = "";
      /**
       * <code>optional string uName = 2;</code>
       */
      public boolean hasUName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string uName = 2;</code>
       */
      public java.lang.String getUName() {
        java.lang.Object ref = uName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUNameBytes() {
        java.lang.Object ref = uName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uName = 2;</code>
       */
      public Builder setUName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uName = 2;</code>
       */
      public Builder clearUName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uName_ = getDefaultInstance().getUName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uName = 2;</code>
       */
      public Builder setUNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        uName_ = value;
        onChanged();
        return this;
      }

      // optional string uPassword = 3;
      private java.lang.Object uPassword_ = "";
      /**
       * <code>optional string uPassword = 3;</code>
       */
      public boolean hasUPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string uPassword = 3;</code>
       */
      public java.lang.String getUPassword() {
        java.lang.Object ref = uPassword_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uPassword = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUPasswordBytes() {
        java.lang.Object ref = uPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uPassword = 3;</code>
       */
      public Builder setUPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uPassword = 3;</code>
       */
      public Builder clearUPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uPassword_ = getDefaultInstance().getUPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uPassword = 3;</code>
       */
      public Builder setUPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uPassword_ = value;
        onChanged();
        return this;
      }

      // optional uint32 uPower = 4;
      private int uPower_ ;
      /**
       * <code>optional uint32 uPower = 4;</code>
       */
      public boolean hasUPower() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 uPower = 4;</code>
       */
      public int getUPower() {
        return uPower_;
      }
      /**
       * <code>optional uint32 uPower = 4;</code>
       */
      public Builder setUPower(int value) {
        bitField0_ |= 0x00000008;
        uPower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uPower = 4;</code>
       */
      public Builder clearUPower() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uPower_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 uGold = 5;
      private int uGold_ ;
      /**
       * <code>optional uint32 uGold = 5;</code>
       */
      public boolean hasUGold() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 uGold = 5;</code>
       */
      public int getUGold() {
        return uGold_;
      }
      /**
       * <code>optional uint32 uGold = 5;</code>
       */
      public Builder setUGold(int value) {
        bitField0_ |= 0x00000010;
        uGold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uGold = 5;</code>
       */
      public Builder clearUGold() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uGold_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 uDiamond = 6;
      private int uDiamond_ ;
      /**
       * <code>optional uint32 uDiamond = 6;</code>
       */
      public boolean hasUDiamond() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 uDiamond = 6;</code>
       */
      public int getUDiamond() {
        return uDiamond_;
      }
      /**
       * <code>optional uint32 uDiamond = 6;</code>
       */
      public Builder setUDiamond(int value) {
        bitField0_ |= 0x00000020;
        uDiamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uDiamond = 6;</code>
       */
      public Builder clearUDiamond() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uDiamond_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:User)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\"f\n\004User\022\013\n\003uId\030\001 \001(\r\022\r\n\005uNa" +
      "me\030\002 \001(\t\022\021\n\tuPassword\030\003 \001(\t\022\016\n\006uPower\030\004 " +
      "\001(\r\022\r\n\005uGold\030\005 \001(\r\022\020\n\010uDiamond\030\006 \001(\rB\036\n\021" +
      "cpgame.demo.protoB\tUserProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_User_descriptor,
              new java.lang.String[] { "UId", "UName", "UPassword", "UPower", "UGold", "UDiamond", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
